version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: cakephp-ecommerce-app
    restart: unless-stopped
    tty: true
    volumes:
      - ../:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www
    networks:
      - cakephp-ecommerce-network

  webserver:
    image: nginx:alpine
    container_name: cakephp-ecommerce-webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ../:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - cakephp-ecommerce-network

  db:
    image: mysql:8
    container_name: cakephp-ecommerce-db
    restart: unless-stopped
    tty: true
    volumes:
      - ../:/var/www
      - ./mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: HardPassword@4657
      MYSQL_TCP_PORT: 3306
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: HardPassword@4657
    networks:
      - cakephp-ecommerce-network

networks:
  cakephp-ecommerce-network:
    driver: bridge
